image: danhdue/shiseido:all

stages:
  - CIChecking

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - chmod +x ./gradlew
  - echo $ANDROID_HOME

CIChecking:
  dependencies: []
  stage: CIChecking
  cache:
    paths:
      - ./.gradle
      - ./build
      - ./app/build
      - ./build-caches
  artifacts:
    paths:
      - .ci-reports
  script:
    - fastlane android run_unitTest
    - fastlane android Build
    - fastlane android beta_distribute
  tags:
    - gitlab-server-docker
